Optionally publish acceleration state
cra-ros-pkg/robot_localization pull request #317
Opened 2016-11-04 10:48 UTC by reinzor

Expose acceleration state via a geometry_msgs/AccelWithCovarianceStamped message. This is configurable by the `publish_acceleration` parameters which defaults to `false`.

#314

2016-11-04 11:09 UTC, ayrton04 requested changes
Looks like a nice addition, thank you. I'd ask that we keep the PR focused on only the changes that need to be made; I give some more detail in the individual comments.

Thank you for the PR!

2016-11-04 11:09 UTC, ayrton04 commented on include/robot_localization/ros_filter.h
> +    bool getFilteredOdometryAndAccelMessage(nav_msgs::Odometry &odomMsg, geometry_msgs::AccelWithCovarianceStamped& accelMsg);
I think I'd prefer that we add a second method for assembling the acceleration message. Then we can fill it conditionally base on the value of `publishAcceleration_`, and we're not changing this method signature.

2016-11-04 11:09 UTC, ayrton04 commented on src/ros_filter.cpp
> +      //! Fill out the odometry message
To keep the PR focused, I'd prefer that we not change anything unless needed.

2016-11-04 11:09 UTC, ayrton04 commented on src/ros_filter.cpp
> +    // Whether we're publishing the world_frame->base_link_frame transform
I realize this is a typo, but I'd rather have a PR that addresses comments and such specifically.

2016-11-04 11:09 UTC, ayrton04 commented on src/ros_filter.cpp
> +    if (publishAcceleration_)
Please use curly braces, even for one-line conditional statements.

2016-11-04 11:09 UTC, ayrton04 commented on src/ros_filter.cpp
> +      nav_msgs::Odometry odomMsg;
As above: if we don't have to change this, I'd prefer that we leave it alone, even if the variable name is admittedly not great. This rename ends up creating a lot of changed lines in the PR that don't actually change any functionality.

2016-11-04 13:16 UTC, reinzor commented
I just processed the comments and committed to make the changes minimal

2016-11-07 09:12 UTC, ayrton04 commented
Looks good. I will test this out and merge. Thanks again!

2016-11-09 16:18 UTC, ayrton04 commented
Just testing PR jobs on the build server. Please ignore the close and open.

2016-11-10 09:38 UTC, ayrton04 commented
Testing PR job again.

2016-11-14 12:01 UTC, ayrton04 commented
Ignore build failure. That's a separate issue with the CMakeLists file. I pulled this down and tested it, and it looks good. Thanks again for the PR!

2016-11-14 12:01 UTC, merged