Feature/adding nodelets
cra-ros-pkg/robot_localization pull request #343
Opened 2017-02-16 16:16 UTC by SGSSGene

Work In Progress. Don't merge.

This is my first attempt to create nodelets. To Test this I wanted to create a test just like the "ekf_localization_node_bag1.test" just for nodelets.

But if I run the test, it fails and I don't know why. I run
`catkin_make run_tests_robot_localization_rostest_test_test_ekf_localization_nodelet_bag1.test`
does any one have an idea?

2017-02-21 10:29 UTC, ayrton04 commented on include/robot_localization/ros_filter.h
> +
Extra space

2017-02-21 10:29 UTC, ayrton04 commented on include/robot_localization/ros_filter.h
> +	//! @brief minimal frequency
Indentation

2017-02-21 10:30 UTC, ayrton04 commented on include/robot_localization/ros_filter.h
> +
Extra spaces. Might want to run roslint on the whole thing.

2017-02-21 10:38 UTC, ayrton04 requested changes
I'll likely have more, and I'm guessing some of these changes are in the other PR, but there are a few things to change.

2017-02-21 10:38 UTC, ayrton04 commented on package.xml
> +  <build_depend>nodelet</build_depend>
Please alphabetize

2017-02-21 10:38 UTC, ayrton04 commented on src/ekf_localization_node.cpp
> +  return EXIT_SUCCESS;
What defines this?

2017-02-21 10:38 UTC, ayrton04 commented on src/ekf_localization_nodelet.cpp
> +  std::auto_ptr<RosEkf> ekf;
Even though this is supported in Kinetic, I'd like all of these changes to not require C++11, as it means I'll have to only allow this in Kinetic, and will have to maintain Indigo separately. If we have no choice, then we'll deal with it, but I'd prefer to support every ROS distribution that's currently not EOL, if possible.

2017-02-21 10:38 UTC, ayrton04 commented on src/ekf_localization_nodelet.cpp
> +    virtual void onInit() {
No cuddled braces. Please see http://wiki.ros.org/CppStyleGuide. I realize the variables  don't adhere to standards, but I try to keep everything else that way.

2017-02-21 10:38 UTC, ayrton04 commented on src/ekf_localization_nodelet.cpp
> +#include <pluginlib/class_list_macros.h>
Can this include go at the top?

2017-02-21 10:38 UTC, ayrton04 commented on src/navsat_transform_nodelet.cpp
> + * Copyright (c) 2014, 2015, 2016, Charles River Analytics, Inc.
Don't need to make this CRA's copyright.

2017-02-28 15:30 UTC, SGSSGene commented on src/ekf_localization_node.cpp
> +  return EXIT_SUCCESS;
This is standard c/c++: http://en.cppreference.com/w/cpp/utility/program/EXIT_status

2017-03-01 13:36 UTC, SGSSGene commented on src/navsat_transform_nodelet.cpp
> + * Copyright (c) 2014, 2015, 2016, Charles River Analytics, Inc.
Good point :-). This will take some time to clarify. Not sure which license I have to apply.

2017-03-01 13:43 UTC, ayrton04 commented on src/navsat_transform_nodelet.cpp
> + * Copyright (c) 2014, 2015, 2016, Charles River Analytics, Inc.
The package license is BSD, so we don't need to change that verbiage, but the copyright holder can be you or your organization. Note that I am not a copyright lawyer, but I'm pretty sure that's how it works. :)

2017-03-01 14:34 UTC, ayrton04 commented on src/ekf_localization_node.cpp
> +  return EXIT_SUCCESS;
Right, but it needs you to `#include <cstdlib>`.

2017-03-01 15:00 UTC, SGSSGene commented on src/ekf_localization_nodelet.cpp
> +  std::auto_ptr<RosEkf> ekf;
std::auto_ptr is c++03. It is not my favorite feature, but seemed better then a naked pointer.
In c++11 you would use std::unique_ptr instead.

2017-08-09 12:10 UTC, merged

2018-07-16 16:04 UTC, bochen87 commented
@ayrton04 Any reason this is not in kinetic?

2018-07-17 06:55 UTC, ayrton04 commented
It represents a pretty major change to the package, and was added well into Kinetic's lifecycle. I don't strictly adhere to the standards that OSRF suggests for managing changes within and across ROS distros, but this certainly seemed like a significant enough change that releasing it in Kinetic seemed questionable.

2018-07-17 06:59 UTC, bochen87 commented
ok, thanks for your explanation. Was just wondering, as it does seem to be a very useful feature!

2018-07-17 07:01 UTC, ayrton04 commented
If you don't mind working from source, the Lunar and Melodic branches will build just fine in Kinetic.

2018-07-17 07:24 UTC, bochen87 commented
ok, thanks for the hint!