Read predict_to_current_time from ROS parameters
cra-ros-pkg/robot_localization pull request #737
Opened 2022-03-08 13:03 UTC by zygfrydw

I have added a parameter `predict_to_current_time` to read the value from ROS parameters, otherwise the member `predict_to_current_time_` was not initialized.

2022-03-08 19:39 UTC, SteveMacenski requested changes
Where is this used?

2022-03-08 20:00 UTC, zygfrydw commented
In the file **ros_filter.cpp** line 584 and 697 (function `RosFilter<T>::integrateMeasurements`) on branch **galactic**

```cpp
bool predict_to_current_time = predict_to_current_time_;
[...]
if (filter_.getInitializedStatus() && predict_to_current_time) {
rclcpp::Duration last_update_delta =
    current_time - filter_.getLastMeasurementTime();

filter_.validateDelta(last_update_delta);
filter_.predict(current_time, last_update_delta);

// Update the last measurement time and last update time
filter_.setLastMeasurementTime(
    filter_.getLastMeasurementTime() +
    last_update_delta);
}
```

2022-04-25 16:37 UTC, ayrton04 commented
Yeah, looks like we just failed to load it. It gets loaded in noetic here:

https://github.com/cra-ros-pkg/robot_localization/blob/87b8d6bf6c94933da9f2f830460fa1c38c651db5/src/ros_filter.cpp#L871

2022-04-25 16:38 UTC, ayrton04 approved these changes

2022-04-25 16:38 UTC, merged